language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
env: PERL_CPANM_OPT="--mirror http://cpan.mirrors.travis-ci.org  --mirror http://cpan.cpantesters.org/ --mirror http://search.cpan.org/CPAN --cascade-search --notest --force --skip-satisfied" ES="localhost:9200"
before_install:
  - export OLD_DIR=`pwd`
  - cd /tmp
  - curl -L  http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.20.2.tar.gz | tar -xz
  - elasticsearch-0.20.2/bin/elasticsearch
  - cd $OLD_DIR
  - "cpanm Dist::Zilla"
  - "dzil authordeps | cpanm"
install: "dzil listdeps | xargs cpanm"
script: "dzil test --release"
